title: ev3lynx727
description: Articles and technical writing
url: "https://ev3lynx727.github.io"
baseurl: "/blog"
permalink: pretty
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - README.md
  - drafts/
  - .gitkeep
